[build-system]
requires = ["scikit-build-core", "cython>=3.1.3", "numpy>=2.2.6"]
build-backend = "scikit_build_core.build"

[project]
name = "algos"
version = "0.1.0"
description = "A package containing algorithms and data structures implemented in Cython"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "cython>=3.1.3",
    "cython-lint>=0.16.7",
    "numpy>=2.2.6",
    "setuptools>=80.9.0",
]

[project.optional-dependencies]
test = ["pytest"]

[dependency-groups]
dev = [
    "pre-commit>=4.5.1",
    "pre-commit-hooks>=6.0.0",
    "pytest>=8.4.1",
    "ruff>=0.12.10",
]

[tool.scikit-build]
wheel.packages = ["src"]

# Tells scikit-build-core to use the installed Cython rather than fetching one
[tool.scikit-build.cmake.define]
CMAKE_BUILD_TYPE = "Release"

[tool.ruff]
# Set the maximum line length to 79.
line-length = 79

[tool.ruff.lint]
# Allow unused variables when underscore-prefixed
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
select = [
    "A",   # flake8-builtins
    "ANN", # flake8-annotations
    "ARG", # flake8-unused arguments
    "BLE", # blind-except
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "I",   # sort imports
    "RET", # flake8-return
    "UP",  # pyupgrade
    "W",   # pycodestyle warnings
]
ignore = [
    "E731",   # Do not assign a lambda expression, use a def
    # "W502",   # Line break occured before binary operator (ignore anti pattern)
    "ANN002", # Missing type annotation for *args
    "ANN003", # Missing type annotation for **kwargs
    "ANN401", # Dynamically typed expressions (typing.Any) are disallowed
]

[tool.ruff.lint.per-file-ignores]
# Allow unused imports in __init__.py files.
"__init__.py" = ["F401", "W292"]

# Do not require typehinting for unit-tests, allow unused arguments
"tests/*.py" = ["ANN", "ARG"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.cython-lint]
max-line-length = 88
ignore = [
    "E731",
    "W503",
    "W504"
]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
python_files = "test_*.py"
addopts = "-v"
